{% set python_min = "3.9" %}
{% set version = "1.7.2" %}

package:
  name: h5netcdf
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/h/h5netcdf/h5netcdf-{{ version }}.tar.gz
  sha256: c2b35a5c2f9d6f0df3dcd1bf43ff6945af284d234bf74a12ed3fec7c0156d644

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=7.0
    - pip
  run:
    - python >={{ python_min }}
    - h5py
    - packaging

test:
  imports:
    - h5netcdf
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/h5netcdf/h5netcdf
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Pythonic interface to netCDF4 via h5py

extra:
  recipe-maintainers:
    - hmaarrfk
    - jhamman
    - ocefpaf
    - shoyer
    - kmuehlbauer
