{% set version = "0.2.2" %}

package:
    name: h5netcdf
    version: {{ version }}

source:
    fn: h5netcdf-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/h/h5netcdf/h5netcdf-{{ version }}.tar.gz
    md5: 5de72a6b8e4cc071ca2154fadf3681e3

build:
    number: 1
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        # This pins to the default channel version as conda-forge's h5py (hdf5) is incompatible with libnetcdf at the moment.
        - h5py 2.6.0 np{{ np }}py{{ py }}_0
    run:
        - python
        # This pins to the default channel version as conda-forge's h5py (hdf5) is incompatible with libnetcdf at the moment.
        - h5py 2.6.0 np{{ np }}py{{ py }}_0

test:
    imports:
        - h5netcdf

about:
    home: https://github.com/shoyer/h5netcdf
    license: BSD-3-Clause
    summary: netCDF4 via h5py

extra:
    recipe-maintainers:
        - jhamman
        - ocefpaf
        - shoyer
