{% set version = "1.3.0" %}

package:
  name: h5netcdf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/h5netcdf/h5netcdf-{{ version }}.tar.gz
  sha256: a171c027daeb34b24c24a3b6304195b8eabbb6f10c748256ed3cfe19806383cf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - setuptools-scm >=7.0
    - pip
  run:
    - python >=3.9
    - h5py
    - packaging

test:
  imports:
    - h5netcdf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/h5netcdf/h5netcdf
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Pythonic interface to netCDF4 via h5py

extra:
  recipe-maintainers:
    - hmaarrfk
    - jhamman
    - ocefpaf
    - shoyer
    - kmuehlbauer
